#!/bin/sh /etc/rc.common

START=99
STOP=1

USE_PROCD=1
PROG=/root/recorder
NAME=recorder


start_service()
{
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param reload_signal SIGHUP
	procd_close_instance
}
