include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-halsamrec
PKG_VERSION:=1.1
PKG_RELEASE:=1

LUCI_TITLE:=HALSAmRec Audio Devices LuCI Interface
LUCI_DESCRIPTION:=LuCI interface for ALSA audio device probing and recorder service control
LUCI_DEPENDS:=+alsa-utils
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
