include $(TOPDIR)/rules.mk

LUCI_TITLE:=HALSAmRec Audio Devices LuCI Interface
LUCI_DEPENDS:=+alsa-utils
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-halsamrec
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot legacy
